<!DOCTYPE html>
<html lang="en" dir="ltr" >
  <head>
    <meta charset="utf-8">
    <title>Carte_Algoritmica</title>
    <link href="style.css" rel="stylesheet" />
    <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />
  </head>
  <body>
	<header class="header">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <img class="logo" src="images/lo.png" alt="">
        <div class="move_buttons">
           
             <a href="Log_in.html"><button class="buttons">Log in</button></a>
             <a href="Sign_up.html"><button class="buttons">Sign up</button></a>
           
           </div>

	</header>


  <nav id="nav">
      <ul>
      <li>
        <a>
        <span>
          <svg width="30" height="30">
            <path d="M0,5 30,5" stroke="#fff" stroke-width="2"/>
            <path d="M0,14 30,14" stroke="#fff" stroke-width="2"/>
            <path d="M0,23 30,23" stroke="#fff" stroke-width="2"/>
          </svg>
        </span>
      </a>
      </li>
        <li><a href="Acasa.html"><Strong>Home</Strong></a></li>
        <li><a href="#contact"><Strong>Contact</Strong></a></li>
        <li style="float:right"><a><input type="text"  placeholder="Search in page..." id="InputSearch" ></a></li>
      </ul>
      </nav>


 <div class="subtitlu" >
 <a href="Acasa.html">CCS</a> -> <a href="Programming Paradigms.html">Programming Paradigms</a> -> <a>Article Design Patern</a>
</div>
	 <br>
        <article>
            <section>
        <table id="table1">
            <tr>
                 <td> Article type: </td>
                 <td> PDF book </td>
            </tr>
            <tr>
                 <td> Name: </td>
                 <td> Design Patterns: Elements of Reusable Object-Oriented Software</td>
            </tr>
            <tr>
                 <td> Authors: </td>
                 <td> Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides</td>
            </tr>
            <tr>
                    <td> Rating: </td>
                    <td>5/5</td>
            </tr>
            <tr>
                    <td> Publisher: </td>
                    <td>Addison-Wesley</td>
           </tr>
           <tr>
                <td>Publication date: </td>
                <td>1994</td>
           </tr>
           <tr>
               <td>Subject</td>
               <td>	Design patterns, software engineering, object-oriented programming</td></tr>
            <tr>
                     <td> Access to buy:</td>
                     <td><a href="https://www.amazon.com/Design-Patterns-Elements-Reusable-Object-Oriented/dp/0201633612">here</a> </td>
            </tr>
            </table>
            
           </section>
        </article>
            <footer> Copyright &copy; Faculty of Computer Science, group A7</footer>
    </body>
</html>
